name: Build and publish Singularity container image
jobs:
  build-and-push:
  runs-on : ubuntu-latest
  steps :
    - name : Checkout code
      uses : actions/checkout@v4
    - name : Set up Docker Buildx
      id : buildx
      uses : docker/setup-buildx-action@v3
    - name : Docker Login to Seqera public CR
      uses : docker/login-action@v3
      with :
        registry : "docker.io"
        username : "hrma017"
        password : ${{ secrets.SEQERA_PUBLIC_CR_PASSWORD }}
    - name : Build and Push Image to public.cr.seqera.io
      with :
        run : |
          cd singularity
          make build
